userland: redo most of the recipes

diff --git a/userland/recipes/bash/recipe b/userland/recipes/bash/recipe
--- a/userland/recipes/bash/recipe
+++ b/userland/recipes/bash/recipe
@@ -1,44 +1,79 @@
 #! /bin/sh
 
-version=5.3
-revision=10
-tarball_url="https://ftpmirror.gnu.org/gnu/bash/bash-${version}.tar.gz"
-tarball_sha512="426702c8b0fb9e0c9956259973ce5b657890fd47f4f807a64febf20077bb48d0b91474ed6e843d2ef277186b46c5fffa79b808da9b48d4ec027d5e2de1b28ed8"
-imagedeps="build-essential bison"
-hostdeps="bootstrap-gcc binutils"
-deps="base ncurses readline"
+_version=5.3
+_patch=15
+version=${_version}.${_patch}
+revision=3
+tarball_url="https://ftp.gnu.org/gnu/bash/bash-${_version}.tar.gz"
+tarball_blake2b="82d1b54322bbd1e8c2a93380f1b2888a42a1d7186e504f41cee705a0fdd41463d8f20baa1755051e1396192f8ebd089524767d933a9e0b5fb76f2588601539bb"
+imagedeps="build-essential"
+hostdeps="gcc-host pkg-config"
+deps="sys-libs ncurses readline"
+
+_get_patch() {
+    TMP_PATCH=$(mktemp)
+    curl -Lo "${TMP_PATCH}" https://ftp.gnu.org/gnu/bash/bash-${_version}-patches/bash$(echo "${_version}" | sed 's/\.//g')-$1
+    if ! b2sum "${TMP_PATCH}" | grep -q $2; then
+        die "b2sum checksum fail for bash patch $1
+        expected $2
+        got      $(b2sum "${TMP_PATCH}")"
+    fi
+    patch -p0 <"${TMP_PATCH}"
+}
+
+early_prepare() {
+    _get_patch 001 ca275ade6a7132d316a4d1ffd401c9bfc6de691c58531385d85087c4d50723aeacb5b4bc7abef0165b4fb3cbed146a0fefd9dae4c99c1547f61618798a772d29
+    _get_patch 002 fec52c475b8126774290eab7a514f8145ae51edab150d413c09f5540719c9578fe1cb99987b6190a9cd82bd947e059c32e740a03d26e9d472af51356cafd8a32
+    _get_patch 003 6bb6f6679726d65f95c11b4ac1fb0729eaebfeef02de06e9fda4e3ac2bb3d328cc6f7fd6e29976a0907390ed6709cd5a0a6046682acbed73eb0470143bf144e1
+    _get_patch 004 6f3dcb7ca264868b235e25296b778152383e0f728a87f462fafb30d3c3e0334f8ac8bd862ed82e117641b34f4bd5bbb89ff118462f8a4d716049b651e6c4b0a6
+    _get_patch 005 792a8f489f36537da9ac1c986ceeed99465cca1740a865c15f8c4942afcc9ee413117f789e18f13daeacd94079425ce0089edbfd4f9f30af56bec0ed15a02dc4
+    _get_patch 006 92e1cac8784c463f143a1bbad088cb6a4451ef5d864f04205831ffe8835b3d5723e4bfc3ca864a77074afcdb14f627c728f796cb85c050c21916c16d1f990f18
+    _get_patch 007 5939ba2b3e0dbd83ecb51b47e71f35e32e7647fad1bedf0f00b73cc279b91de977b1cae7314b87483f62cbc0888a739b39528f0ca882a26bc81cc9b9898336e3
+    _get_patch 008 7ebe5ac77d3697da01ad7beb88a8fdaeac3ac2fb671cc5151ce10428044b4f5fd7ea13e35c91eef1a7d6027f9053a57a27864d5f6a935d48d6cd2be6a9239233
+    _get_patch 009 09ddf6b605d409142a4107bd52c8b48a91a225d65b867b5074c8b5359d0b1012d2f50e54d1d5636b3413431cf4840d6bd34f9c84f062f3ead96eeaf912127532
+    _get_patch 010 0ca1df76a06c59dc773e603930747000cfa249219adb79cecb173e36986ccd2b2f49ced66702abbcec25ace05bafc109e23565cd19a202ce05840516d7c3aa70
+    _get_patch 011 21fe0e08c06257ea415c4ff697a44251460eb636667300cbb3946c77bbbdb67c667fd20bd561bb7635ee3917b13d0860234c6c159d786542e8403e7cedeba986
+    _get_patch 012 bb3e4ef57170185d3e0be91211632cb5c9a776a71848d2b44a13982bc91f68c2f07ed0aa52b377004f1b872a2b38e5292970d738bdda13fffcd0120c77c4042d
+    _get_patch 013 133ee6faf3e62fa5f8b99aafef114fc2038dfa96bad769bf9ab2f7129d5d52f19d7d3ca1b3e7ac1d12c883ed276ac06b832c61f5aea134de184a6e3bb95cf4fa
+    _get_patch 014 cb525fe154e792c467e06f0d930a09466f6f3cf5a688bf13abd7bbb64410f93f6c797e186609f9540c64355d5fd78d0be4473348d948907284bf631f2b60a381
+    _get_patch 015 5d333c73b891910df4bf13c28fa0cc493dcadadb5c51a240501c5ab450b83673d75baece5c8112b937520cacfc726248ede1d30dba6b60075b88408b585b9f3f
+}
 
 prepare() {
     autotools_recursive_regen
 }
 
 configure() {
-    bash_cv_func_sigsetjmp=missing \
-    bash_cv_must_reinstall_sighandlers=no \
-    ac_cv_func_mmap_fixed_mapped=yes \
-    ac_cv_func_setvbuf_reversed=no \
-    CC_FOR_BUILD=gcc \
-    CFLAGS_FOR_BUILD="-std=gnu17 -g" \
-    CFLAGS="${TARGET_CFLAGS} \
-        -DDEFAULT_PATH_VALUE='\"/usr/bin:/bin\"' \
-        -DSTANDARD_UTILS_PATH='\"/usr/bin:/bin\"'" \
-        autotools_configure \
-            --disable-nls \
-            --disable-job-control \
-            --enable-readline \
-            --with-curses \
-            --with-installed-readline \
-            --without-bash-malloc
+        CC_FOR_BUILD=gcc \
+        CFLAGS_FOR_BUILD="-O2 -std=gnu17" \
+        bash_cv_getcwd_malloc=yes \
+        bash_cv_func_sigsetjmp=missing \
+    autotools_configure \
+        CFLAGS="$TARGET_CFLAGS \
+            -DDEFAULT_PATH_VALUE='\"/usr/local/sbin:/usr/local/bin:/usr/bin\"' \
+            -DSTANDARD_UTILS_PATH='\"/usr/bin\"' \
+            -DSYS_BASHRC='\"/etc/bash.bashrc\"' \
+            -DSYS_BASH_LOGOUT='\"/etc/bash.bash_logout\"' \
+            -DNON_INTERACTIVE_LOGIN_SHELLS \
+        " \
+        --with-curses \
+        --enable-readline \
+        --without-bash-malloc \
+        --with-installed-readline
 }
 
 build() {
-    make -j"${parallelism}"
+    make -j${parallelism}
 }
 
 package() {
     make install DESTDIR="${dest_dir}"
+    ln -s bash "${dest_dir}${prefix}"/bin/sh
+    ln -s bash "${dest_dir}${prefix}"/bin/rbash
 
-    mkdir -p "${dest_dir}/bin"
-    ln -s ../usr/bin/bash "${dest_dir}/bin/bash"
-    ln -s bash "${dest_dir}/bin/sh"
+    mkdir -p "${dest_dir}"/etc
+    cp -v "${recipe_dir}"/bash.bashrc "${dest_dir}"/etc/
+    cp -v "${recipe_dir}"/bash.bash_logout "${dest_dir}"/etc/
+
+    post_package_strip
 }
